rm_ros2_manual:
  ros__parameters:
    robot_type: "standard"
    max_linear_x:
      x: [ 50.0, 70.0, 90.0 ]
      y: [ 5.0, 7.0,9.0 ]
    max_linear_y:
      x: [ 50.0, 70.0, 90.0 ]
      y: [ 5.0, 7.0,9.0 ]
    max_angular_z:
      x: [ 50.0, 70.0, 90.0 ]
      y: [ 5.0, 7.0,9.0 ]
    topic: "/cmd_vel"
    qos: 10.0
    power_limit_topic: "/cmd_chassis"
    controllers:
      main_controllers:
        - gimbal_controller
